function select_loader(d){$(d).find('option').remove();$(d).append('<option value="">Loading...</option>');}
function changeurgency_order(doc_id,urgency){var root_url=$('#root_url').val();var addonprice=$("#assignment_subject").find(':selected').data('addonprice');$.ajax({type:"POST",url:""+root_url+"ajax/deadline.php",data:{assignment:doc_id,addonprice:addonprice,urgency:urgency},beforeSend:function(){if($("#urgency").val()==''){select_loader("#urgency");}},success:function(a){$("#urgency_div").html(a);price_calculater_order();}});}
function ass_select(ass_id,group_unit,group_id,words,w,q){$("#wait").css("display","block");$(".overlays_ajax").css("display","block");$('#assignment').val(ass_id);$('#group_unit_hidden').val(group_unit);var pages_count_slected=$("#pages_count").val();if(pages_count_slected==null||pages_count_slected==''){pages_count_slected=$("#post_calculator_page").val();}
changewords_order(group_unit,ass_id,pages_count_slected);if(group_id==4||group_id==8||group_id==11){$('#style').parent().parent().hide();}else{$('#style').parent().parent().show();}
if(group_id==4){var no_of_q=$('#no_of_q').val();var no_of_w=$('#no_of_w').val();if(no_of_q!=''&&no_of_w!=''){var pages_count_slected=Math.ceil((no_of_q*no_of_w)/words);$('#pages_count').val(pages_count_slected);}else{pages_count_slected=1;$('#pages_count').val(pages_count_slected);if(('#no_of_q').val()==''){$('.no_of_q').val(w);}
if(('#no_of_w').val()==''){$('.no_of_w').val(q);}}
$('#words_counts').val(words);$('#words_txt').val(words+' Words');$('#page_words').html(pages_count_slected+' Pages');$('.q_w_calcu').show();$('#pages_count').parent().parent().hide();}else{$('#pages_count').parent().parent().show();$('.q_w_calcu').hide();if(pages_count_slected==''){pages_count_slected='1';$('#pages_count').val(pages_count_slected)}}
var pages_count_txt=$("#pages_count option:selected").text();}
function price_currency(currency){$('.currradioa').removeClass('selected');$('#currencies').val(currency);$('.currradio'+currency).addClass('selected');price_calculater_order();}
function price_calculater_order(){var addonprice=$("#assignment_subject").find(':selected').data('addonprice');var group_id=$("#ass_group_list option:selected").val();var root_url=$("#root_url").val();$("#order_now_wait").show();$("#orderContinue").hide();$.ajax({type:"POST",url:root_url+"ajax/price.php",data:{service:group_id,extraprice:addonprice,document_id:$("#assignment").val(),assignment_subject_nm:$("#assignment_subject_nm").val(),page:$("#pages_count").val(),words:$("#words_counts").val(),curr:$("#currencies").val(),urgency:$("#urgency").val(),lavel:$("#lavel").val(),from:$("#calculator_type").val(),root_url:$("#root_url").val()},beforeSend:function(){$("#order_now_wait").hide();$("#orderContinue").show();$(".overlays_ajax").css("display","block");},success:function(a){$("#side_contain_tot").html(a),$("#wait").css("display","none");$(".overlays_ajax").css("display","none");}});}
function show_total(){var a=$("#totalprice").val();var c=$("#curr_position").val();if(a>0){var b=$("#curr_symbole_ajsx").val();}else{var b='';}
$("#totx").html(a),"pre"==c?($(".curr_show_pre").html(b),$(".curr_show_post").html("")):"post"==c&&($(".curr_show_post").html(b),$("#curr_show_pre").html(""));}
function get_subject_list(d,root_url,assignment_subject_nm){var g_id=$(d).val();var unit_tag=$('option:selected',d).attr('unit_tag');if(g_id){select_loader("#assignment_subject");$.ajax({url:root_url+"ajax/topic.php",type:'POST',data:{g_id:g_id,unit_tag:unit_tag,assignment_subject_nm:assignment_subject_nm,},beforeSend:function(){$('#get_subject select').val('');},success:function(html){$('#get_subject').html(html);}});}}
function exact_page_count_get(pages_count_slected){var cc=0;$("#pages_count option").each(function(){var op_value=$(this).attr("value");if(op_value>parseInt(pages_count_slected)&&cc==0){cc=op_value;}});if(cc==0){cc=1;}
return cc;}
function caclulate_words(words,d){var no_of_q=$('.no_of_q').val();var no_of_w=$('.no_of_w').val();if(no_of_q!=''&&no_of_w!=''){var pages_count_slected=Math.ceil((no_of_q*no_of_w)/words);$('#pages_count').val(pages_count_slected);var words=pages_count_slected*250;$('#words_counts').val(words);$('#words_txt').val(words+' Words');var ass_id=$('.assignment').val();var group_unit=$('.group_unit_hidden').val();changewords_order(group_unit,ass_id,pages_count_slected);}}
function turnitin_free_amount(currencies,b,count){if(currencies==1){var turnitin_cost='7.50';}else if(currencies==3){var turnitin_cost='5.50';}else if(currencies==4){var turnitin_cost='10.00';}
$('#turnitin_add').html(b+' 0');$('#free-turnitin').html('('+b+' '+turnitin_cost*count+')');}
function show_total_after_turnitun(currencies){var a=$("#totalprice").val(),b=$("#curr_symbole_ajsx").val(),c=$("#curr_position").val(),d=$("#turnitin_report_price").val(),e=parseFloat(a)+parseFloat(d);e=e.toFixed(2);turnitin_free_amount(currencies,b,1);"pre"==c?(f=b+' '+e,$("#tot_price_after_turnitin").html(f)):"post"==c&&(g=e+' '+b,$("#tot_price_after_turnitin").html(g));}
function loadingBtn(load)
{if(load==1)
{$('#order_now_wait').show();$('#orderContinue').hide();}else
{$('#order_now_wait').hide();$('#orderContinue').show();}}
function popupShow(showID)
{$('#cust-info .signup').css("display","none");setTimeout(function(){$('#cust-info #'+showID).css("display","block");$('#cust-info').fancybox({'clickSlide':false,smallBtn:true,toolbar:false,clickOutside:true,}).trigger('click');},200);}
function calculator(d){var validation=ValidateFrom(d);if(validation==true){loadingBtn(1);var form=d[0];var formData=new FormData(form);var root_url=$('#root_url').val();$('.error').empty();var existcust_STATUS=$('#existcust_STATUS').val();var cust_enable=$('#cust_enable').val();var email_cust=$('#email_cust').val();if(email_cust=='')
{loadingBtn(0);popupShow('socialLogin');}else
{var calculator_type=$('#calculator_type').val();$.ajax({type:'POST',enctype:'multipart/form-data',url:root_url+"submit/lead-submit.php",data:formData,cache:false,contentType:false,processData:false,success:function(data){loadingBtn(0);$('.firststepbtn').hide();$('#submit-signUp-step1').show();if(existcust_STATUS=='2'||data=='0'){window.location.replace(root_url+"order-thanks.php");}else if((calculator_type=='order_now'&&existcust_STATUS==0)||(cust_enable==0&&existcust_STATUS==1)){$('#cust_email').val(email_cust);$('#cust_email').prop('readonly',true);var phone_student=$('#phone_student').val();var country_code=$('#country_code').val();if(phone_student)
{$('#order-cust-2 .country_code_list').val(country_code);$('#order-cust-2 #cust_phone').val(phone_student);}
popupShow('otherInfo');}else if(calculator_type=='order_now'&&existcust_STATUS==1){$('#existotherInfo').find('#email_id_login').val(email_cust);popupShow('existotherInfo');}else{window.location.replace(root_url+"order-now.php");}},});}}}
function login_existing_customer(d){var validation=ValidateFrom(d);if(validation==true){var form=d[0];var formData=new FormData(form);var root_url=$('#root_url').val();$('.errorlogin').empty();$('.thirdstepbtn').toggle();$.ajax({type:'POST',enctype:'multipart/form-data',url:root_url+"submit/login_existing_customer.php",data:formData,cache:false,contentType:false,processData:false,success:function(data){if(data==0){$('.thirdstepbtn').toggle();d.find('.errorlogin').html('Invalid Username And Password');}else{window.location.replace(data);}},});}}
function OrdrCustInfoStep2(d){var validation=ValidateFrom(d);if(validation==true){var form=d[0];var formData=new FormData(form);var root_url=$('#root_url').val();$('.error').empty();$('.secondstepbtn').toggle();$.ajax({type:'POST',enctype:'multipart/form-data',url:root_url+"submit/custInfo-submit.php",data:formData,cache:false,contentType:false,processData:false,success:function(data){$('.secondstepbtn').toggle();if(data=='0')
{window.location.replace(root_url+"order-thanks.php");}else
{popupShow('existotherInfo');$('#cust-info').fancybox().trigger('click');$('#order_now_wait').hide();$('#orderContinue').show();}},});}}