$('#mobilechat').on('click',function(){$zopim.livechat.window.show()})
window.mobileCheck=function(){let check=false;(function(a){if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,4)))check=true;})(navigator.userAgent||navigator.vendor||window.opera);return check;};function setCookie(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toUTCString();document.cookie=cname+"="+cvalue+";"+expires+";path=/";}
function getCookie(cname){var name=cname+"=";var decodedCookie=decodeURIComponent(document.cookie);var ca=decodedCookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1);}
if(c.indexOf(name)==0){return c.substring(name.length,c.length);}}
return "";}
function ValidatePhone(str){if(/^\+?([0-9]{2,3})\)?[- ]?([0-9]{5,20})$/.test(str)){return(true);}
return(false);}
function ValidateName(name){if(/^[A-Za-z ]+$/.test(name)){return(true);}
return(false);}
function ValidateEmail(a){if(/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/.test(a)){return(true);}
return(false);}
(function($){$.fn.focusTextToEnd=function(){this.focus();var $thisVal=this.val();this.val('').val($thisVal);return this;}}(jQuery));$(':input').on('input',function(){$(this).css('border','').parent().find('.error').remove();$('#termerror').text('');});$(document).ajaxSuccess(function(){$(':input').on('input',function(){$(this).css('border','').parent().find('.error').remove();$('#termerror').text('');});});$('input[name=name], input[name=name1]').on('input',function(){$(this).attr('maxlength','40');this.value=this.value.replace(/[^a-zA-Z ]/g,'').replace(/(\..*)\./g,'$1');})
$('input[name=email], input[name=email1]').on('input',function(){$(this).removeAttr('type').attr('type','text');this.value=this.value.replace(/[^a-zA-Z0-9.@.!#$%&'*+-/=?^_`{|}~]/g,'');$(this).focusTextToEnd();})
$('input[name=phone], input[name=contact1]').on('input',function(){$(this).attr('maxlength','15');this.value=this.value.replace(/[^0-9 ]/g,'').replace(/(\..*)\./g,'$1');})
$('input[name=q]').on('input',function(){this.value=this.value.replace(/[^a-zA-Z& -]/g,'').replace(/(\..*)\./g,'$1');});$('textarea[name=contain],input[name=search_text],input[name=title],input[name=user], input[name=topic],textarea[name=message], textarea[name=message1] ,textarea[name=requirement]').on('input',function(){this.value=this.value.replace(/[^a-zA-Z0-9& -]/g,'').replace(/(\..*)\./g,'$1');});var root_url=$('#root_url').val();function ValidateFrom(obj,emalType){if(emalType==undefined){emalType='';}
var valid=true;var ele=$(obj).find('input[type=text],input[type=number],input[name=questionfile],input[type=password],input[type=file],input[type=email],input[type=tel],input[type=search],input[type=checkbox],textarea, select')
$(ele).each(function(i,value){var name=$(this).attr('name');var value=$(this).val();$(this).find('.errorshake').removeClass("errorshake");$(this).parent().find('.error').remove();if($(this).is(":visible")&&(name!='requirement'&&name!='style'&&name!='discription')){if($(this).is('select')&&value==''){valid=sendError(this,'Please Select This Option');}else{if(name=='email'){if(value==''){if(emalType=='forget'){valid=sendError(this,'Please Provide Your Registered Mail Id');}else{valid=sendError(this,'Please Provide Your Email');}}else if(ValidateEmail(value)==false){valid=sendError(this,'Please Enter Valid Email');}}else if(name=='name'&&ValidateName(value)==false){valid=sendError(this,'Please Provide Valid Name');}else if(name=='phone'){if(value==''){valid=sendError(this,'Please Provide Your Phone Number');}else if(ValidatePhone(value)==false){$('#'+name+'error').text('Please Enter Valid Phone Number');$(this).focus();valid=sendError(this,'Please Enter Valid Phone');}}else if(name=='cust_phone'){if(value==''){valid=sendError(this,'Please Provide Your Phone Number');}else if(ValidatePhone(value)==false){$('#'+name+'error').text('Please Enter Valid Phone Number');$(this).focus();valid=sendError(this,'Please Enter Valid Phone');}}else if(name=='q'&&ValidateName(value)==false){valid=sendError(this,'Please Enter Valid Keyword');}else if(name=='password'){if(value==''){valid=sendError(this,'Please Enter password');}}else if(name=='cpassword'){if(value==''){valid=sendError(this,'Please Enter Confirm password');}else if(value!=$('input[name=password]').val()){valid=sendError(this,'Confirm password Not Match');}}else if(name=='term'){if($(this).prop("checked")==false){$('#termerror').text('Please accept our term and Condition').show();$('html, body').animate({scrollTop:$(this).offset().top},2000);valid=valid=sendError(this,'');}}else if(name=='captcha'||name=='captcha1'){var result=$.ajax({type:'post',url:root_url+'ajax.php',async:false,data:{action:'Captchacehck',ajax:'ajax',captcha:value},success:function(data){return data=JSON.parse(data);if(data.status==0){}}}).responseText;result=JSON.parse(result);if(result.status==0){valid=sendError($('[name='+name+']'),result.message)}}
if(name=='questionfile[]'&&$('#questionfile')[0].files.length===0){valid=sendError($('#questionfile').parent().parent(),'Please Select File');}else if(name=='files[]'){if($('#UploadFiles').val()==''||$('#UploadFiles').val()=='[]'){}}else if(name!='phone_student'){if(value==''){valid=sendError(this,'Please Provide Valid Information ddd')}}}}
return valid;});if(valid==true){}
return valid;}
function sendError(ele,msg){$('.error').remove();$(':input').css('border','');$(ele).focus().css('border','solid 1px red');$(ele).addClass("errorshake");return false;}
$(" #email").keypress(function(e){if(e.which==13){$('#emailcheck').trigger('click');}});$("#password").keypress(function(e){if(e.which==13){$('#continuelogin').trigger('click');}});$('#emailcheck').click(function(){$('.error').remove();var email=$('#email').val();if(ValidateEmail(email)==true){$('.error').text('');;$('#email').attr('readonly','true');var data={email:email}
$.ajax({type:'post',url:root_url+'customer_panel/Users/usercheck',data:data,async:false,beforeSend:function(){$('#emailcheckloader').show();},success:function(result){result=JSON.parse(result);if(result.status==0){$('.social').hide();$('#emailcheck').hide();$('.show-reg').hide();if(result.filed==1){$('#popHeading').text('Login');$('#changeemail').hide();$('.showlogin').show();}else{$('#popHeading').text('Sign Up');$('#changeemail').show();$('.show-reg').show();$('#continueregister').show();}
$('#emailcheckloader').hide();}else if(result.status==1){window.location='dashboard';}else if(result.status==2){var message=JSON.parse(result);sendError('#password',message.message);}}});}else{sendError('#email','Enter Valid Email Id');}});function SampleForm(root_url,d){var country=$('#'+d).find('.country_code_list').val();var phone=$('#mobile').val();var email=$("#email").val();var source=$("#sample_source").val();var url=$("#sample_url").val();var sample_title=$("#sample_title").val();$('.error').empty();$('.error').text('');var submit=1;$('#email').css('border','1px solid #ccc');$('#mobile').css('border','1px solid #ccc');if(phone==''){sendError('#mobile','Enter Valid Mobile no.');submit=0;}else if(!ValidatePhone(phone)){submit=0;sendError('#mobile','Enter Valid Mobile no.');}
if(email==''){$('#email').focus();submit=0;sendError('#email','Enter Valid Email Id');}else if(!ValidateEmail(email)){$('#email').focus();submit=0;sendError('#email','Enter Valid Email Id');}
if(submit==1){$('#submit-btn-contact').hide();$('.error').empty();$('.error').text('');$('.success').empty();$('.success').html('<div style="text-align:center" class="loader-sub" ><img border="0" src="'+root_url+'images/loading_windows.gif" width="40" height="40" /></div>');$('#email').css('border','1px solid #ccc');$('#mobile').css('border','1px solid #ccc');$.post(""+root_url+"submit/sample_submit.php",{phone:phone,email:email,country:country,source:source,sample_title:sample_title,async:false,},function(data){$('#mobile').val('');$('#email').val('');setTimeout(function(){$('.sample-download-box').remove();setCookie('sampleCookie','true',30);},1000);swal("Success!","Thank You ,Details has been successfully submitted","success");});}}
function AnswerForm(root_url,d){var country=$('#'+d).find('.country_code_list').val();var phone=$('#mobile').val();var email=$("#email").val();var source=$("#sample_source").val();var url=$("#sample_url").val();var sample_title=$("#sample_title").val();$('.error').empty();$('.error').text('');var submit=1;$('#email').css('border','1px solid #ccc');$('#mobile').css('border','1px solid #ccc');if(phone==''){sendError('#mobile','Enter Valid Mobile no.');submit=0;}else if(!ValidatePhone(phone)){submit=0;sendError('#mobile','Enter Valid Mobile no.');}
if(email==''){$('#email').focus();submit=0;sendError('#email','Enter Valid Email Id');}else if(!ValidateEmail(email)){$('#email').focus();submit=0;sendError('#email','Enter Valid Email Id');}
if(submit==1){$('#submit-btn-contact').hide();$('.error').empty();$('.error').text('');$('.success').empty();$('.success').html('<div style="text-align:center" class="loader-sub" ><img border="0" src="'+root_url+'images/loading_windows.gif" width="40" height="40" /></div>');$('#email').css('border','1px solid #ccc');$('#mobile').css('border','1px solid #ccc');$.post(""+root_url+"submit/answer_submit.php",{phone:phone,email:email,country:country,source:source,sample_title:sample_title,async:false,},function(data){$('#mobile').val('');$('#email').val('');setTimeout(function(){$('.sample-download-box').remove();setCookie('answerCookie','true',30);},1000);swal("Success!","Thank You. Details have been successfully submitted","success");});}}
function review_form(root_url,d){var rev_name=$('#rev_name').val();var email=$('#email').val();var title=$("#title").val();var message=$('#message').val();var rating=$("#rating_val").val();$('.error').empty();var submit=1;if(message==''){$('#message').focus();sendError('#messsage','Enter Message!');submit=0;}
if(title==''){$('#title').focus();submit=0;sendError('#title','Enter valid Title!');}
if(email==''){$('#email').focus();submit=0;sendError('#email','Enter Valid Email Id');}else if(!ValidateEmail(email)){$('#email').focus();submit=0;sendError('#email','Enter Valid Email Id');}
if(rev_name==''){$('#rev_name').focus();submit=0;sendError('#rev_name','Enter valid Name!');}
if(submit==1){$('.loader-button').show();$('.error').empty();$.ajax({type:'post',url:root_url+"submit/review_submit.php",data:{name:rev_name,email:email,title:title,message:message,rating:rating,},beforeSend:function(){$('.review-button').toggle();},success:function(){$.fancybox.close();swal("Success!","Thank You. Review has been successfully submitted","success");$('.review-button').toggle();$('.review_form_field').val('');}});}}
function callback(root_url,d){var country=$(d).parent().find('.country_code_list').val();var phone=$('#callback_phone').val();var email=$("#callback_email").val();var name=$("#callback_name").val();var source=$("#callback_source").val();var message=$("#callback_reason").val();$('.error').empty();$('.error').text('');var submit=1;if(message==''){$('#callback_reason').focus();sendError('#callback_reason','Enter Message!');submit=0;}
if(phone==''){sendError('#callback_phone','Enter Valid Mobile no.');submit=0;}else if(!ValidatePhone(phone)){submit=0;sendError('#callback_phone','Enter Valid Mobile no.');}
if(email==''){$('#callback_email').focus();submit=0;sendError('#callback_email','Enter Valid Email Id');}else if(!ValidateEmail(email)){$('#callback_email').focus();submit=0;sendError('#callback_email','Enter Valid Email Id');}
if(name==''){$('#callback_name').focus();submit=0;sendError('#callback_name','Enter valid Name!');}
if(submit==1){$('.error').empty();$('.error').text('');$('.success').empty();$('.loader-button').show();$('#callback_email').css('border','1px solid #ccc');$('#callback_phone').css('border','1px solid #ccc');$.ajax({type:'POST',enctype:'multipart/form-data',url:root_url+'submit/contact_submit.php',data:{name:name,phone:phone,country:country,email:email,source:source,message:message,},beforeSend:function(){$('.contact-button').toggle();},success:function(result){if(result=='success'){$('.contact-button').toggle();$('.formfields').val('');$.fancybox.close();swal("Success!","Thank You ,Your request has been successfully submitted","success");}}});}}
function setcookiejs(name){var d=new Date();d.setTime(d.getTime()+(1*24*60*60*1000));var e="expires="+d.toGMTString();document.cookie=name+"=true;"+e;clearInterval(interval);}
var interval=null;var mouseX=0;var mouseY=0;var popupCounter=0;document.addEventListener("mousemove",function(e){mouseX=e.clientX;mouseY=e.clientY;});$(document).mouseleave(function(){if(mouseY<100){if(popupCounter<1){$('#offerpopupdiv').fancybox({clickSlide:false,afterClose:function(){setcookiejs('offerPopupCookie');}}).trigger('click');$('#orderpopup').fancybox().trigger('click');}
popupCounter++;}});if(!mobileCheck()&&!getCookie('notifi')){window.setInterval(function(){callStickynotification()},60000);setTimeout(function(){callStickynotification();setTimeout(function(){$('.sticky-popup').removeClass("active");},10000);},30000);function callStickynotification(){var root_url=$('#root_url').val();$.ajax({type:'post',url:root_url+'include/getnotification.php',data:'',dataType:'json',async:false,success:function(result){if(result.country){$('#noticountry').html(result.country);}
$('.sticky-popup').addClass("active");}});}
$('.stickyclose').click(function(){$('.sticky-popup').removeClass("active");setCookie('notifi','true',1);})}
$('#completeorder').click(function(){setcookiejs('order');})